server:
  port: 8761

spring:
  application:
    name: eureka-service    #应用名称（集群下相同）
  security:
    user:
      name: root
      password: 123456

eureka:
  instance:
    hostname: eureka-service01    #主机名称
    prefer-ip-address: true
    instance-id: ${spring.cloud..client.ip-address}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8762/eureka/
