##本身不提供服务
server:
  port: 9090

spring:
  application:
    name: service-consumer-product  #应用名称 集群下相同


  security:
    user:
      name: root
      password: 123456

    #注册中心地址
    eurekaService:
      hostname01: localhost:8761
      hostname02: localhost:8762

eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${spring.security.eurekaService.hostname01}/eureka/,
                   http://${spring.security.user.name}:${spring.security.user.password}@${spring.security.eurekaService.hostname02}/eureka/

