server:
  port: 7070

spring:
  application:
    name: service-provider-product  #应用名称 集群下相同


  security:
    user:
      name: root
      password: 123456

    #注册中心地址
    eurekaService:
      hostname01: localhost:8761
      hostname02: localhost:8762

eureka:
  instance:
    prefer-ip-address: true   #是否使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${spring.security.eurekaService.hostname01}/eureka/,
                   http://${spring.security.user.name}:${spring.security.user.password}@${spring.security.eurekaService.hostname02}/eureka/

#停服端口
management:
  endpoints:
    web:
      exposure:
        include: shutdown   #开启shutdown 端点

  endpoint:
    shutdown:
      enabled: true   #开启shutdown